import { MistakeDefinition, PlaybookSetup, Trade, TradeRule } from '../types/trade';
import { generatePreTradeChartSvg, generatePostTradeChartSvg } from './chartGenerator';

export const SYSTEM_MISTAKES: MistakeDefinition[] = [
  // Entry Faults
  {
    id: 'm-entry-fomo',
    category: 'entry',
    code: 'ENTRY_FOMO',
    label: 'FOMO Impulse Entry',
    description: 'Entered impulsively without structural confirmation due to fear of missing the move.',
    isSystemDefault: true,
  },
  {
    id: 'm-entry-chasing',
    category: 'entry',
    code: 'ENTRY_CHASING',
    label: 'Chasing Extended Price',
    description: 'Entered after substantial price extension away from logical invalidation, worsening R:R.',
    isSystemDefault: true,
  },
  {
    id: 'm-entry-frontrun',
    category: 'entry',
    code: 'ENTRY_FRONT_RUN',
    label: 'Front-Running Confirmation',
    description: 'Jumped in before key timeframe candle closed or trigger condition printed.',
    isSystemDefault: true,
  },
  // Risk & Management Faults
  {
    id: 'm-risk-widen-stop',
    category: 'risk_management',
    code: 'RISK_WIDEN_STOP',
    label: 'Widening Stop Loss',
    description: 'Pushed stop loss further out to avoid taking a planned loss on adverse excursion.',
    isSystemDefault: true,
  },
  {
    id: 'm-risk-oversized',
    category: 'risk_management',
    code: 'RISK_OVERSIZED',
    label: 'Oversized Position Size',
    description: 'Violated 1R dollar risk ceiling; sized excessively for account tier.',
    isSystemDefault: true,
  },
  {
    id: 'm-risk-premature-be',
    category: 'risk_management',
    code: 'RISK_PREMATURE_BE',
    label: 'Premature Breakeven Move',
    description: 'Moved stop loss to breakeven before 1st scale-out milestone, getting chopped out.',
    isSystemDefault: true,
  },
  // Exit Faults
  {
    id: 'm-exit-fear-close',
    category: 'exit',
    code: 'EXIT_EARLY_FEAR',
    label: 'Fear-Based Early Close',
    description: 'Closed winner prematurely on minor counter-tick due to P&L anxiety instead of technical signal.',
    isSystemDefault: true,
  },
  {
    id: 'm-exit-greedy-target',
    category: 'exit',
    code: 'EXIT_GREEDY_TARGET',
    label: 'Greedily Removing Target',
    description: 'Cancelled planned limit order hoping for unrealistic runner, giving back entire open gain.',
    isSystemDefault: true,
  },
];

export const PLAYBOOK_SETUPS: PlaybookSetup[] = [
  {
    id: 'setup-fvg-sweep',
    name: 'Liquidity Sweep & FVG Retest',
    description: 'High timeframe buy/sell-side liquidity purge followed by aggressive displacement and Fair Value Gap return.',
    targetRR: 3.2,
    winRate: 64.0,
    totalTrades: 42,
    expectancyR: 1.48,
    isRetired: false,
  },
  {
    id: 'setup-orb',
    name: 'Opening Range Breakout (ORB)',
    description: 'Initial 15-minute high/low expansion during the New York market open session with relative volume surge.',
    targetRR: 2.5,
    winRate: 52.0,
    totalTrades: 31,
    expectancyR: 0.82,
    isRetired: false,
  },
  {
    id: 'setup-vwap-mean-rev',
    name: 'VWAP 2-Sigma Mean Reversion',
    description: 'Exhaustion at the 2nd standard deviation band of session VWAP targeting mean reversion to session volume POC.',
    targetRR: 1.8,
    winRate: 48.0,
    totalTrades: 19,
    expectancyR: -0.15,
    isRetired: true, // Retired due to negative mathematical edge!
  },
  {
    id: 'setup-trend-pullback',
    name: '2-Leg Institutional Pullback',
    description: 'Measured move pullback to 50-61.8% Golden Pocket Fibonacci confluence on 1H trend alignment.',
    targetRR: 2.8,
    winRate: 60.0,
    totalTrades: 28,
    expectancyR: 1.28,
    isRetired: false,
  },
];

export const UNIVERSAL_RULES: TradeRule[] = [
  {
    id: 'rule-1',
    ruleText: 'Waited for execution timeframe candle closure confirmation?',
    isMandatory: true,
    weight: 2,
  },
  {
    id: 'rule-2',
    ruleText: 'Risk strictly constrained within 1.00R maximum loss ceiling?',
    isMandatory: true,
    weight: 3,
  },
  {
    id: 'rule-3',
    ruleText: 'Setup aligns directly with an approved Playbook strategy model?',
    isMandatory: true,
    weight: 2,
  },
  {
    id: 'rule-4',
    ruleText: 'No revenge or impulse entry within 10 minutes of prior loss?',
    isMandatory: true,
    weight: 3,
  },
  {
    id: 'rule-5',
    ruleText: 'Original Stop-Loss untouched (never moved outward)?',
    isMandatory: true,
    weight: 3,
  },
];

// Seeded Empirical Trades
export const INITIAL_TRADES: Trade[] = [
  {
    id: 'trade-001',
    accountName: 'Apex 50k Funded #1402',
    setupName: 'Liquidity Sweep & FVG Retest',
    instrument: 'NQ',
    assetClass: 'futures',
    direction: 'long',
    session: 'ny_am',
    anchorTimeframe: '1H',
    executionTimeframe: '2m',
    plannedEntry: 18240.50,
    plannedStop: 18210.00,
    plannedTarget: 18338.00,
    plannedRR: 3.20,
    preChartUrl: generatePreTradeChartSvg({
      ticker: 'NQ 100 E-mini',
      timeframe: '2m',
      direction: 'long',
      entry: 18240.50,
      stop: 18210.00,
      target: 18338.00,
      setupName: 'Liquidity Sweep & FVG',
    }),
    thesisNotes: 'London low sweep followed by 5m bullish displacement leaving a clean Fair Value Gap. Targeting prior day high liquidity pool.',
    executedEntry: 18241.50,
    executedStop: 18210.00,
    positionSize: 2, // 2 contracts
    entryTimestamp: '2026-09-04T09:42:00Z',
    neuroState: 'calm_centered',
    slippageOffset: 1.00,
    executedExit: 18337.50,
    exitTimestamp: '2026-09-04T10:18:00Z',
    grossPnl: 3840.00,
    commissionFees: 9.20,
    netPnl: 3830.80,
    postChartUrl: generatePostTradeChartSvg({
      ticker: 'NQ 100 E-mini',
      timeframe: '2m',
      direction: 'long',
      entry: 18241.50,
      stop: 18210.00,
      target: 18338.00,
      exitPrice: 18337.50,
      realizedR: 3.14,
      outcomeType: 'target_hit',
    }),
    narrativeWorked: 'Patience paid off. Held full size through the 10:00 AM macro volatility candle without flinching.',
    narrativeFailed: 'Slight 1-point slippage on market fill due to high opening volume.',
    narrativeLesson: 'Using resting limit orders inside the 50% FVG mean threshold saves $40 per contract.',
    initialRiskDollars: 1220.00,
    realizedR: 3.14,
    isFullyCompliant: true,
    ruleResponses: [
      { ruleId: 'rule-1', ruleText: 'Waited for execution candle close?', passed: true },
      { ruleId: 'rule-2', ruleText: 'Risk strictly constrained under 1R?', passed: true },
      { ruleId: 'rule-3', ruleText: 'Setup aligns with approved playbook?', passed: true },
      { ruleId: 'rule-4', ruleText: 'No revenge or impulse entry?', passed: true },
      { ruleId: 'rule-5', ruleText: 'Original Stop-Loss untouched?', passed: true },
    ],
    mistakes: [],
    createdAt: '2026-09-04T10:25:00Z',
  },
  {
    id: 'trade-002',
    accountName: 'Apex 50k Funded #1402',
    setupName: 'Opening Range Breakout (ORB)',
    instrument: 'ES',
    assetClass: 'futures',
    direction: 'long',
    session: 'ny_am',
    anchorTimeframe: '15m',
    executionTimeframe: '1m',
    plannedEntry: 5410.25,
    plannedStop: 5402.00,
    plannedTarget: 5435.00,
    plannedRR: 3.00,
    preChartUrl: generatePreTradeChartSvg({
      ticker: 'ES S&P 500',
      timeframe: '1m',
      direction: 'long',
      entry: 5410.25,
      stop: 5402.00,
      target: 5435.00,
      setupName: 'ORB Breakout',
    }),
    thesisNotes: '15-minute IB high breakout with heavy volume delta in cumulative volume index.',
    executedEntry: 5412.00,
    executedStop: 5402.00,
    positionSize: 4,
    entryTimestamp: '2026-09-04T10:35:00Z',
    neuroState: 'fomo_urge',
    slippageOffset: 1.75,
    executedExit: 5417.50, // Closed early out of fear!
    exitTimestamp: '2026-09-04T10:48:00Z',
    grossPnl: 1100.00,
    commissionFees: 18.40,
    netPnl: 1081.60,
    postChartUrl: generatePostTradeChartSvg({
      ticker: 'ES S&P 500',
      timeframe: '1m',
      direction: 'long',
      entry: 5412.00,
      stop: 5402.00,
      target: 5435.00,
      exitPrice: 5417.50,
      realizedR: 0.54,
      outcomeType: 'early_close',
    }),
    narrativeWorked: 'The structural premise was 100% correct; price immediately expanded toward 5435 target.',
    narrativeFailed: 'Panicked on a single 1-minute red wick and manually slapped the flat button.',
    narrativeLesson: 'Hands off mouse once scale 1 is hit. Let trailing stop do its job.',
    initialRiskDollars: 2000.00,
    realizedR: 0.54,
    isFullyCompliant: false, // Rule violated: Early fear close leak
    ruleResponses: [
      { ruleId: 'rule-1', ruleText: 'Waited for execution candle close?', passed: true },
      { ruleId: 'rule-2', ruleText: 'Risk strictly constrained under 1R?', passed: true },
      { ruleId: 'rule-3', ruleText: 'Setup aligns with approved playbook?', passed: true },
      { ruleId: 'rule-4', ruleText: 'No revenge or impulse entry?', passed: true },
      { ruleId: 'rule-5', ruleText: 'Original Stop-Loss untouched?', passed: true },
    ],
    mistakes: [
      {
        mistakeId: 'm-exit-fear-close',
        code: 'EXIT_EARLY_FEAR',
        label: 'Fear-Based Early Close',
        category: 'exit',
        severity: 'moderate',
        costOfMistakeR: 2.46, // Leaked 2.46R (planned 3.00R - realized 0.54R)
        costOfMistakeFiat: 4920.00,
        triggerEmotion: 'Watching the open P&L dollar fluctuation rather than the candle price action',
        ruleTakeaway: 'Must minimize open P&L column; trade the technical chart strictly',
      },
      {
        mistakeId: 'm-entry-chasing',
        code: 'ENTRY_CHASING',
        label: 'Chasing Extended Price',
        category: 'entry',
        severity: 'minor',
        costOfMistakeR: 0.25,
        costOfMistakeFiat: 500.00,
        triggerEmotion: 'Fear of missing the opening expansion bar',
        ruleTakeaway: 'Wait for 1-minute retest of breakout bar high before entering',
      },
    ],
    createdAt: '2026-09-04T10:55:00Z',
  },
  {
    id: 'trade-003',
    accountName: 'Personal Interactive Brokers',
    setupName: '2-Leg Institutional Pullback',
    instrument: 'NVDA',
    assetClass: 'equities',
    direction: 'long',
    session: 'ny_lunch',
    anchorTimeframe: '4H',
    executionTimeframe: '5m',
    plannedEntry: 122.50,
    plannedStop: 120.80,
    plannedTarget: 128.00,
    plannedRR: 3.24,
    preChartUrl: generatePreTradeChartSvg({
      ticker: 'NVDA',
      timeframe: '5m',
      direction: 'long',
      entry: 122.50,
      stop: 120.80,
      target: 128.00,
      setupName: '2-Leg Pullback',
    }),
    thesisNotes: 'NVDA tested the daily 21 EMA with rising market breadth. Sized for $500 risk.',
    executedEntry: 122.50,
    executedStop: 120.80,
    positionSize: 294, // 294 shares
    entryTimestamp: '2026-09-03T13:15:00Z',
    neuroState: 'calm_centered',
    slippageOffset: 0.00,
    executedExit: 127.85,
    exitTimestamp: '2026-09-03T15:45:00Z',
    grossPnl: 1572.90,
    commissionFees: 3.00,
    netPnl: 1569.90,
    postChartUrl: generatePostTradeChartSvg({
      ticker: 'NVDA',
      timeframe: '5m',
      direction: 'long',
      entry: 122.50,
      stop: 120.80,
      target: 128.00,
      exitPrice: 127.85,
      realizedR: 3.14,
      outcomeType: 'target_hit',
    }),
    narrativeWorked: 'Flawless execution. Let the trade play out during the entire afternoon session.',
    narrativeFailed: 'None. Textbook playbook execution.',
    narrativeLesson: 'Midday pullbacks in trending mega-cap tech provide low stress high-expectancy setups.',
    initialRiskDollars: 500.00,
    realizedR: 3.14,
    isFullyCompliant: true,
    ruleResponses: [
      { ruleId: 'rule-1', ruleText: 'Waited for execution candle close?', passed: true },
      { ruleId: 'rule-2', ruleText: 'Risk strictly constrained under 1R?', passed: true },
      { ruleId: 'rule-3', ruleText: 'Setup aligns with approved playbook?', passed: true },
      { ruleId: 'rule-4', ruleText: 'No revenge or impulse entry?', passed: true },
      { ruleId: 'rule-5', ruleText: 'Original Stop-Loss untouched?', passed: true },
    ],
    mistakes: [],
    createdAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'trade-004',
    accountName: 'Apex 50k Funded #1402',
    setupName: 'VWAP 2-Sigma Mean Reversion',
    instrument: 'NQ',
    assetClass: 'futures',
    direction: 'short',
    session: 'ny_pm',
    anchorTimeframe: '15m',
    executionTimeframe: '1m',
    plannedEntry: 18450.00,
    plannedStop: 18475.00, // 25 pt planned stop ($500 per contract)
    plannedTarget: 18400.00,
    plannedRR: 2.00,
    preChartUrl: generatePreTradeChartSvg({
      ticker: 'NQ 100 E-mini',
      timeframe: '1m',
      direction: 'short',
      entry: 18450.00,
      stop: 18475.00,
      target: 18400.00,
      setupName: 'VWAP Reversion',
    }),
    thesisNotes: 'Fading the 2-sigma band during late afternoon rally. High risk counter-trend.',
    executedEntry: 18452.00,
    executedStop: 18510.00, // Widened stop by 35 points! Severe rule violation!
    positionSize: 2,
    entryTimestamp: '2026-09-02T14:40:00Z',
    neuroState: 'revenge_tilted',
    slippageOffset: 2.00,
    executedExit: 18510.00,
    exitTimestamp: '2026-09-02T15:10:00Z',
    grossPnl: -2320.00,
    commissionFees: 9.20,
    netPnl: -2329.20,
    postChartUrl: generatePostTradeChartSvg({
      ticker: 'NQ 100 E-mini',
      timeframe: '1m',
      direction: 'short',
      entry: 18452.00,
      stop: 18475.00,
      target: 18400.00,
      exitPrice: 18510.00,
      realizedR: -2.33,
      outcomeType: 'stopped_out',
    }),
    narrativeWorked: 'Nothing worked. Violated my core risk protocol by moving my stop when price pushed against me.',
    narrativeFailed: 'Widened stop loss because I refused to accept a clean -1R loss.',
    narrativeLesson: 'Moving a stop loss is account suicide. Never drag a stop order again.',
    initialRiskDollars: 1000.00,
    realizedR: -2.33,
    isFullyCompliant: false,
    ruleResponses: [
      { ruleId: 'rule-1', ruleText: 'Waited for execution candle close?', passed: false },
      { ruleId: 'rule-2', ruleText: 'Risk strictly constrained under 1R?', passed: false },
      { ruleId: 'rule-3', ruleText: 'Setup aligns with approved playbook?', passed: true },
      { ruleId: 'rule-4', ruleText: 'No revenge or impulse entry?', passed: false },
      { ruleId: 'rule-5', ruleText: 'Original Stop-Loss untouched?', passed: false },
    ],
    mistakes: [
      {
        mistakeId: 'm-risk-widen-stop',
        code: 'RISK_WIDEN_STOP',
        label: 'Widening Stop Loss',
        category: 'risk_management',
        severity: 'catastrophic',
        costOfMistakeR: 1.33, // Realized -2.33R instead of clean -1.00R
        costOfMistakeFiat: 1330.00,
        triggerEmotion: 'Ego refusal to register a loss on the day',
        ruleTakeaway: 'Hard stop entered at order submission. Hardware stop never gets edited.',
      },
      {
        mistakeId: 'm-entry-fomo',
        code: 'ENTRY_FOMO',
        label: 'FOMO Impulse Entry',
        category: 'entry',
        severity: 'severe',
        costOfMistakeR: 1.00,
        costOfMistakeFiat: 1000.00,
        triggerEmotion: 'Urge to make back prior scratch trade',
        ruleTakeaway: 'Retire counter-trend VWAP mean reversion during trending afternoons.',
      },
    ],
    createdAt: '2026-09-02T15:30:00Z',
  },
  {
    id: 'trade-005',
    accountName: 'Apex 50k Funded #1402',
    setupName: 'Liquidity Sweep & FVG Retest',
    instrument: 'EUR/USD',
    assetClass: 'forex',
    direction: 'short',
    session: 'london',
    anchorTimeframe: '1H',
    executionTimeframe: '5m',
    plannedEntry: 1.08500,
    plannedStop: 1.08620,
    plannedTarget: 1.08140,
    plannedRR: 3.00,
    preChartUrl: generatePreTradeChartSvg({
      ticker: 'EUR/USD',
      timeframe: '5m',
      direction: 'short',
      entry: 1.08500,
      stop: 1.08620,
      target: 1.08140,
      setupName: 'London High Sweep',
    }),
    thesisNotes: 'Asian session high sweep into London open with clean bearish shift in market structure.',
    executedEntry: 1.08500,
    executedStop: 1.08620,
    positionSize: 5.0, // 5 lots
    entryTimestamp: '2026-09-01T08:15:00Z',
    neuroState: 'calm_centered',
    slippageOffset: 0.00,
    executedExit: 1.08150,
    exitTimestamp: '2026-09-01T10:45:00Z',
    grossPnl: 1750.00,
    commissionFees: 25.00,
    netPnl: 1725.00,
    postChartUrl: generatePostTradeChartSvg({
      ticker: 'EUR/USD',
      timeframe: '5m',
      direction: 'short',
      entry: 1.08500,
      stop: 1.08620,
      target: 1.08140,
      exitPrice: 1.08150,
      realizedR: 2.88,
      outcomeType: 'target_hit',
    }),
    narrativeWorked: 'Clean follow through. Sized appropriately to absorb 12 pip invalidation risk.',
    narrativeFailed: 'Exited 1 pip shy of true swing low liquidity pool.',
    narrativeLesson: 'London session sweeps provide the highest reliability win rate in the entire playbook.',
    initialRiskDollars: 600.00,
    realizedR: 2.88,
    isFullyCompliant: true,
    ruleResponses: [
      { ruleId: 'rule-1', ruleText: 'Waited for execution candle close?', passed: true },
      { ruleId: 'rule-2', ruleText: 'Risk strictly constrained under 1R?', passed: true },
      { ruleId: 'rule-3', ruleText: 'Setup aligns with approved playbook?', passed: true },
      { ruleId: 'rule-4', ruleText: 'No revenge or impulse entry?', passed: true },
      { ruleId: 'rule-5', ruleText: 'Original Stop-Loss untouched?', passed: true },
    ],
    mistakes: [],
    createdAt: '2026-09-01T11:00:00Z',
  },
];
